---
- hosts: database
  remote_user: root
  vars:
    mysqlservice: mysqld
    mysql_port: 3306
    wp_db_name: wordpress
    wp_db_user: wordpress
    wp_db_password: secret
  roles:
    - common
    - mariadb
